# Generated by Django 5.1.2 on 2024-11-05 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('total_reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(max_length=20)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rental_price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability_status', models.CharField(default='available', max_length=20)),
                ('features', models.JSONField()),
                ('images', models.ManyToManyField(related_name='bikes', to='HoppzyApp.image')),
                ('insurance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HoppzyApp.insurance')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='HoppzyApp.location')),
                ('ratings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HoppzyApp.ratings')),
            ],
        ),
    ]
