# Generated by Django 5.1.2 on 2024-11-05 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoppzyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HoppzyApp.bike'),
        ),
    ]
